# Generated by Django 4.2.30 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PdEscalationPolicy",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_escalation_policy",
            },
        ),
        migrations.CreateModel(
            name="PdService",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("team_id", models.TextField(blank=True, null=True)),
                ("escalation_policy_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_service",
            },
        ),
        migrations.CreateModel(
            name="PdSyncState",
            fields=[
                ("resource", models.TextField(primary_key=True, serialize=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_full_sync_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_sync_state",
            },
        ),
        migrations.CreateModel(
            name="PdTeam",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_team",
            },
        ),
        migrations.CreateModel(
            name="PdUser",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("region", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_user",
            },
        ),
        migrations.CreateModel(
            name="PdLogEntry",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("incident_id", models.TextField()),
                ("type", models.TextField(blank=True, null=True)),
                ("at", models.DateTimeField()),
                ("agent_user_id", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_log_entry",
                "indexes": [
                    models.Index(
                        fields=["incident_id", "type", "at"], name="ix_pd_log_ita"
                    ),
                    models.Index(fields=["agent_user_id"], name="ix_pd_log_agent"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PdIncident",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("incident_number", models.IntegerField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("urgency", models.TextField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
                ("service_id", models.TextField(blank=True, null=True)),
                ("escalation_policy_id", models.TextField(blank=True, null=True)),
                ("team_id", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_user_id", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_incident",
                "indexes": [
                    models.Index(fields=["created_at"], name="ix_pd_incident_created"),
                    models.Index(fields=["service_id"], name="ix_pd_incident_service"),
                    models.Index(
                        fields=["assigned_user_id"], name="ix_pd_incident_assigned"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PdAlert",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("incident_id", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("alertname", models.TextField(blank=True, null=True)),
                ("cloud", models.TextField(blank=True, null=True)),
                ("juju_model", models.TextField(blank=True, null=True)),
                ("juju_model_uuid", models.TextField(blank=True, null=True)),
                ("charm", models.TextField(blank=True, null=True)),
                ("juju_unit", models.TextField(blank=True, null=True)),
                ("severity", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("raw_details", models.JSONField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "pd_alert",
                "indexes": [
                    models.Index(fields=["incident_id"], name="ix_pd_alert_incident"),
                    models.Index(fields=["alertname"], name="ix_pd_alert_alertname"),
                    models.Index(fields=["cloud"], name="ix_pd_alert_cloud"),
                    models.Index(fields=["juju_model"], name="ix_pd_alert_model"),
                    models.Index(fields=["charm"], name="ix_pd_alert_charm"),
                    models.Index(fields=["created_at"], name="ix_pd_alert_created"),
                ],
            },
        ),
    ]
