# Generated by Django 4.2.30 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JiraChangelog",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("issue_key", models.TextField()),
                ("field", models.TextField()),
                ("from_value", models.TextField(blank=True, null=True)),
                ("to_value", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField()),
                ("author_account_id", models.TextField(blank=True, null=True)),
                ("author_name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_changelog",
            },
        ),
        migrations.CreateModel(
            name="JiraIssue",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("jira_id", models.BigIntegerField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("current_status", models.TextField(blank=True, null=True)),
                ("current_priority", models.TextField(blank=True, null=True)),
                ("assignee_account_id", models.TextField(blank=True, null=True)),
                ("assignee_name", models.TextField(blank=True, null=True)),
                ("reporter_account_id", models.TextField(blank=True, null=True)),
                ("reporter_name", models.TextField(blank=True, null=True)),
                ("area", models.TextField(blank=True, null=True)),
                ("sub_area", models.TextField(blank=True, null=True)),
                ("pulse", models.TextField(blank=True, null=True)),
                ("is_pr_mp", models.BooleanField(default=False)),
                ("labels", models.JSONField(blank=True, null=True)),
                ("jira_updated_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_issue",
            },
        ),
        migrations.CreateModel(
            name="JiraSyncState",
            fields=[
                ("resource", models.TextField(primary_key=True, serialize=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_full_sync_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_sync_state",
            },
        ),
        migrations.CreateModel(
            name="JiraUser",
            fields=[
                ("account_id", models.TextField(primary_key=True, serialize=False)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("region", models.CharField(max_length=8)),
                ("is_external", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "jira_user",
            },
        ),
        migrations.CreateModel(
            name="JiraWorklog",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("issue_key", models.TextField()),
                ("time_spent_seconds", models.IntegerField()),
                ("started_at", models.DateTimeField()),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_worklog",
                "indexes": [
                    models.Index(fields=["started_at"], name="ix_jira_worklog_started"),
                    models.Index(fields=["issue_key"], name="ix_jira_worklog_issue"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JiraStatusInterval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("issue_key", models.TextField()),
                ("status", models.TextField(blank=True, null=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_status_interval",
                "indexes": [
                    models.Index(
                        fields=["issue_key", "valid_from"], name="ix_jira_stat_if"
                    ),
                    models.Index(
                        fields=["status", "valid_from", "valid_to"],
                        name="ix_jira_stat_span",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JiraPriorityInterval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("issue_key", models.TextField()),
                ("priority", models.TextField(blank=True, null=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "jira_priority_interval",
                "indexes": [
                    models.Index(
                        fields=["issue_key", "valid_from"], name="ix_jira_pri_if"
                    ),
                    models.Index(
                        fields=["priority", "valid_from", "valid_to"],
                        name="ix_jira_pri_span",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JiraIssueLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_key", models.TextField()),
                ("label", models.TextField()),
            ],
            options={
                "db_table": "jira_issue_label",
                "indexes": [models.Index(fields=["label"], name="ix_jira_label")],
            },
        ),
        migrations.AddConstraint(
            model_name="jiraissuelabel",
            constraint=models.UniqueConstraint(
                fields=("issue_key", "label"), name="uq_jira_issue_label"
            ),
        ),
        migrations.AddIndex(
            model_name="jiraissue",
            index=models.Index(fields=["created_at"], name="ix_jira_issue_created"),
        ),
        migrations.AddIndex(
            model_name="jiraissue",
            index=models.Index(fields=["current_status"], name="ix_jira_issue_status"),
        ),
        migrations.AddIndex(
            model_name="jiraissue",
            index=models.Index(fields=["area", "sub_area"], name="ix_jira_issue_area"),
        ),
        migrations.AddIndex(
            model_name="jiraissue",
            index=models.Index(fields=["is_pr_mp"], name="ix_jira_issue_prmp"),
        ),
        migrations.AddIndex(
            model_name="jirachangelog",
            index=models.Index(
                fields=["issue_key", "field", "changed_at"],
                name="ix_jira_changelog_ifa",
            ),
        ),
    ]
