# Generated by Django 6.0.5 on 2026-05-13 11:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Environment name, e.g. amer-prod-launchpad', max_length=255, unique=True)),
                ('git_path', models.CharField(help_text='Relative path in is-infrastructure, e.g. services/definitions/compute/foo.yaml', max_length=512)),
                ('region', models.CharField(blank=True, db_index=True, help_text='Geographic region: amer, apac, emea, edge', max_length=50, null=True)),
                ('owner', models.CharField(blank=True, help_text='Team slug, e.g. is, webdesign, snapstore', max_length=255, null=True)),
                ('team', models.CharField(blank=True, db_index=True, help_text='Team slug (synonym for owner)', max_length=255, null=True)),
                ('oncall_handle', models.CharField(blank=True, help_text='PagerDuty service ID or Mattermost handle', max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=100, null=True)),
                ('env_type', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development'), ('lab', 'Lab')], db_index=True, max_length=20)),
                ('criticality_tier', models.IntegerField(blank=True, help_text='1=business critical, 2=important, 3=best effort', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('data_classification', models.CharField(blank=True, choices=[('pii', 'PII'), ('internal', 'Internal'), ('public', 'Public')], max_length=20, null=True)),
                ('compliance_scope', models.JSONField(blank=True, default=list, help_text="List of compliance frameworks, e.g. ['soc2', 'iso27001']")),
                ('charm_versions', models.JSONField(blank=True, default=dict, help_text='{"postgresql": "14/stable", "vault": "1.8/edge"}')),
                ('declared_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last parser run')),
                ('last_git_commit', models.CharField(blank=True, help_text='SHA that triggered the last parse', max_length=40, null=True)),
                ('status', models.CharField(choices=[('provisioning', 'Provisioning'), ('active', 'Active'), ('degraded', 'Degraded'), ('maintenance', 'Maintenance'), ('decommissioning', 'Decommissioning'), ('archived', 'Archived')], db_index=True, default='provisioning', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, help_text='From cmdb label or git blame', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='null = live; set when manifest deleted', null=True)),
                ('maintenance_window', models.JSONField(blank=True, help_text='{"day": "sunday", "start": "02:00", "end": "06:00", "tz": "UTC"}', null=True)),
                ('runbook_url', models.URLField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('last_good_commit', models.CharField(blank=True, help_text='Last SHA that reconciled cleanly', max_length=40, null=True)),
                ('last_good_reconcile', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud', models.CharField(blank=True, help_text='ps5, ps6, ps7, ps8, microcloud-drs, edge-tel, edge-et3', max_length=50, null=True)),
                ('service_primitive', models.CharField(blank=True, choices=[('compute', 'Compute'), ('iam', 'IAM'), ('network', 'Network'), ('storage', 'Storage')], db_index=True, max_length=20, null=True)),
                ('service_class', models.CharField(blank=True, help_text='machine_model, container_model, database, kubernetes_cluster, etc.', max_length=100, null=True)),
                ('juju_controller', models.CharField(blank=True, help_text='Name of Juju controller managing this environment', max_length=255, null=True)),
                ('juju_series', models.CharField(blank=True, help_text="Juju version, e.g. '3.5' or '3.6'", max_length=20, null=True)),
                ('juju_controller_stage', models.CharField(blank=True, help_text='production, staging, migration, etc.', max_length=50, null=True)),
                ('bastion_server', models.CharField(blank=True, help_text='Hostname of bastion server', max_length=255, null=True)),
                ('risk_group', models.CharField(blank=True, help_text="Risk group classification, typically 'stable'", max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cia_owner', models.EmailField(blank=True, help_text='Individual owner from cia_assessment.asset.owner', max_length=254, null=True)),
                ('cia_risk_owner', models.EmailField(blank=True, max_length=254, null=True)),
                ('cia_custodian', models.CharField(blank=True, help_text='Team slug from cia_assessment.asset.custodian', max_length=255, null=True)),
                ('slo_level', models.CharField(blank=True, help_text='IS24x5, IS24x7, etc.', max_length=50, null=True)),
                ('slo_rto', models.IntegerField(blank=True, help_text='Recovery Time Objective in seconds', null=True)),
                ('live', models.BooleanField(blank=True, help_text='If false, environment is declared but not yet provisioned', null=True)),
            ],
            options={
                'db_table': 'environments',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'env_type', 'status'], name='environment_region_f41d65_idx'), models.Index(fields=['team'], name='environment_team_82ef6c_idx'), models.Index(fields=['service_primitive', 'service_class'], name='environment_service_daf7d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_name', models.CharField(db_index=True, help_text='Environment that has the dependency', max_length=255)),
                ('depends_on_name', models.CharField(db_index=True, help_text='Environment that is depended upon', max_length=255)),
                ('dependency_type', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('declared', 'Declared')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'environment_dependencies',
                'indexes': [models.Index(fields=['depends_on_name'], name='environment_depends_554f28_idx')],
                'unique_together': {('environment_name', 'depends_on_name')},
            },
        ),
        migrations.CreateModel(
            name='PlacementHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment_name', models.CharField(db_index=True, max_length=255)),
                ('primary_node', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_node', models.CharField(blank=True, max_length=255, null=True)),
                ('juju_model', models.CharField(blank=True, max_length=255, null=True)),
                ('juju_units', models.JSONField(blank=True, default=list, help_text='[{"unit": "postgresql/0", "machine": "3"}]')),
                ('source', models.CharField(choices=[('juju-api', 'Juju API'), ('kubectl', 'Kubernetes API')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'placement_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['environment_name', '-recorded_at'], name='placement_h_environ_82874c_idx')],
            },
        ),
    ]
