# Generated by Django 6.0.5 on 2026-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='compute_architecture',
            field=models.CharField(blank=True, help_text='Compute architecture: amd64, arm64, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='control_plane_size',
            field=models.CharField(blank=True, help_text='K8s control plane size: small, medium, large', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='control_plane_units',
            field=models.IntegerField(blank=True, help_text='K8s control plane unit count (typically 3)', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='database_size',
            field=models.CharField(blank=True, help_text='Database size: xsmall, small, medium, large, custom', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='network_size',
            field=models.IntegerField(blank=True, help_text='Network CIDR prefix length (e.g., 24, 27)', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='postgresql_major_version',
            field=models.CharField(blank=True, help_text='PostgreSQL major version (for databases)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='quotas',
            field=models.JSONField(blank=True, default=dict, help_text='Resource quotas: {"cores": 80, "ram": 212992, "instances": 22, "gigabytes": 1160, ...}'),
        ),
        migrations.AddField(
            model_name='environment',
            name='worker_groups',
            field=models.JSONField(blank=True, default=list, help_text='K8s worker groups: [{"name": "k8s-worker", "size": "large", "units": 3}]'),
        ),
    ]
