# Generated by Django 6.0.5 on 2026-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_environment_compute_architecture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='accessing_iam_groups',
            field=models.JSONField(blank=True, default=list, help_text='IAM groups that access this environment'),
        ),
        migrations.AddField(
            model_name='environment',
            name='accessing_juju_models',
            field=models.JSONField(blank=True, default=list, help_text='Juju models that access this environment'),
        ),
        migrations.AddField(
            model_name='environment',
            name='allow_dedicated_cpu',
            field=models.BooleanField(blank=True, help_text='Whether dedicated CPU is allowed', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='allow_gpu_passthrough',
            field=models.BooleanField(blank=True, help_text='Whether GPU passthrough is allowed', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='allow_vgpu',
            field=models.BooleanField(blank=True, help_text='Whether vGPU is allowed', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='builder_workloads',
            field=models.BooleanField(blank=True, help_text='Whether builder workloads are allowed', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='cluster',
            field=models.CharField(blank=True, help_text='K8s cluster name for container_model environments', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='data_integrator_accessing_juju_model',
            field=models.JSONField(blank=True, default=list, help_text='Data integrator models accessing this'),
        ),
        migrations.AddField(
            model_name='environment',
            name='datastore',
            field=models.CharField(blank=True, help_text='Datastore type or name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='enable_cilium_ingress',
            field=models.BooleanField(blank=True, help_text='Whether Cilium ingress is enabled', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='enable_exposed_companion',
            field=models.BooleanField(blank=True, help_text='Whether exposed companion is enabled', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='extra_network_peers',
            field=models.JSONField(blank=True, default=list, help_text='List of additional network peers'),
        ),
        migrations.AddField(
            model_name='environment',
            name='extra_subnet',
            field=models.CharField(blank=True, help_text='Additional subnet configuration', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='gitops_model_management',
            field=models.JSONField(blank=True, default=dict, help_text='GitOps configuration for model management'),
        ),
        migrations.AddField(
            model_name='environment',
            name='grant_team_access',
            field=models.BooleanField(blank=True, help_text='Whether to grant team access', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='iam_groups',
            field=models.JSONField(blank=True, default=list, help_text='IAM groups with access: ["is-platform-services-team"]'),
        ),
        migrations.AddField(
            model_name='environment',
            name='ingress_addresses',
            field=models.JSONField(blank=True, default=list, help_text='Public ingress addresses: ["example.com", "*.example.com"]'),
        ),
        migrations.AddField(
            model_name='environment',
            name='jaas_managed',
            field=models.BooleanField(blank=True, help_text='Whether managed by JAAS', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='juju_model_config',
            field=models.JSONField(blank=True, default=dict, help_text='Juju model config: {"juju-http-proxy": "...", ...}'),
        ),
        migrations.AddField(
            model_name='environment',
            name='k8s_models',
            field=models.JSONField(blank=True, default=list, help_text='List of K8s models'),
        ),
        migrations.AddField(
            model_name='environment',
            name='kube_apiserver_extra_sans',
            field=models.JSONField(blank=True, default=list, help_text='Extra SANs for kube-apiserver certificate'),
        ),
        migrations.AddField(
            model_name='environment',
            name='legacy_certificates_charm',
            field=models.BooleanField(blank=True, help_text='Whether using legacy certificates charm', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='manage_flavor_access',
            field=models.BooleanField(blank=True, help_text='Whether flavor access is managed', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='network_type',
            field=models.CharField(blank=True, help_text='isolated, shared, etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='openstack_credential_access',
            field=models.BooleanField(blank=True, help_text='Whether OpenStack credential access is granted', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='postgresql_use_local_storage',
            field=models.BooleanField(blank=True, help_text='Whether PostgreSQL uses local storage', null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='remote_cmr_models',
            field=models.JSONField(blank=True, default=list, help_text='Remote CMR models this environment uses'),
        ),
        migrations.AddField(
            model_name='environment',
            name='requester',
            field=models.CharField(blank=True, help_text='Person who requested this environment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='environment',
            name='role_account_lp_users',
            field=models.JSONField(blank=True, default=list, help_text='Launchpad user IDs for role accounts'),
        ),
        migrations.AddField(
            model_name='environment',
            name='services',
            field=models.JSONField(blank=True, default=list, help_text='Services deployed in this environment'),
        ),
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.CharField(blank=True, help_text='User associated with environment (for personal envs)', max_length=255, null=True),
        ),
    ]
