# Generated by Django 4.2.30 on 2026-05-14 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0005_cloudcapacity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cloudcapacity',
            new_name='cloud_capac_cloud_n_ea626d_idx',
            old_name='cloud_capacity_cloud_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='environment',
            new_name='environment_team_70e1e0_idx',
            old_name='environment_team_arch_idx',
        ),
        migrations.RenameIndex(
            model_name='environment',
            new_name='environment_cloud_acb349_idx',
            old_name='environment_cloud_arch_idx',
        ),
    ]
