# Generated by Django 4.2.30 on 2026-06-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netbox", "0001_initial"),
        (
            "environments",
            "0006_rename_cloud_capacity_cloud_arch_idx_cloud_capac_cloud_n_ea626d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="primary_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical node hosting the primary unit (from placement).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_environments",
                to="netbox.node",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="secondary_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Physical node hosting the secondary/standby unit, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_environments",
                to="netbox.node",
            ),
        ),
    ]
