# Generated by Django 4.2.30 on 2026-06-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0007_environment_primary_node_environment_secondary_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="k8s_distribution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ck8s", "Canonical Kubernetes (CK8s)"),
                    ("ck8s-jenkins-aas", "Jenkins aaS on CK8s"),
                    ("legacy-k8s", "Legacy k8s (pre-CK8s)"),
                ],
                db_index=True,
                help_text="Kubernetes distribution, derived from charm signature / naming. CK8s = deploys the k8s/k8s-worker charms; jenkins-aas is a CK8s subtype; legacy-k8s = pre-CK8s (microk8s / charmed-k8s).",
                max_length=20,
                null=True,
            ),
        ),
    ]
