# Generated by Django 4.2.30 on 2026-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0008_environment_k8s_distribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="cached_dependents_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Number of environments that depend on this one (cached).",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="cached_depends_on",
            field=models.TextField(
                blank=True,
                help_text="Comma-joined names of juju models this env depends on (cached).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="host_aggregate",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OpenStack host aggregate of the env's primary node (cached).",
                max_length=100,
                null=True,
            ),
        ),
    ]
