# Generated by Django 4.2.30 on 2026-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0009_environment_cached_dependents_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='consumer_team',
            field=models.CharField(blank=True, db_index=True, help_text="Real consuming team (CIA-owner's home team for aaS; else team).", max_length=255, null=True),
        ),
    ]
