# Generated by Django 4.2.30 on 2026-06-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0010_environment_consumer_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="gitops_enabled",
            field=models.BooleanField(
                blank=True,
                help_text="gitops_model_management.enabled — whether GitOps management is enabled.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="gitops_managed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if a gitops_model_management block is declared (reconciled via GitOps).",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="gitops_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="is-terraform-modules subpaths consumed by this env's model (resolved on disk for is-terraform-models envs), e.g. ['subordinates', 'juju/applications/lego'].",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="gitops_path",
            field=models.CharField(
                blank=True,
                help_text="Path of the terraform model within the gitops repo, e.g. models/prod-is-vault-ps7.",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="gitops_repo",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="terraform-models repo managing this env, e.g. is-terraform-models.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="gitops_suspended",
            field=models.BooleanField(
                blank=True,
                help_text="gitops_model_management.suspend — whether reconciliation is currently suspended.",
                null=True,
            ),
        ),
    ]
