# Generated by Django 4.2.30 on 2026-06-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environments", "0011_environment_gitops_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharmRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charm",
                    models.CharField(
                        db_index=True,
                        help_text="Charmhub charm name, e.g. postgresql",
                        max_length=255,
                    ),
                ),
                (
                    "track",
                    models.CharField(
                        help_text="Channel track, e.g. 14, latest", max_length=64
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        help_text="Channel risk: stable/candidate/beta/edge",
                        max_length=20,
                    ),
                ),
                (
                    "latest_revision",
                    models.IntegerField(
                        blank=True,
                        help_text="Highest revision published to this channel; null if unknown",
                        null=True,
                    ),
                ),
                (
                    "latest_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Version string of the latest revision",
                        max_length=255,
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When that revision was released to the channel",
                        null=True,
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this row was refreshed from Charmhub",
                    ),
                ),
            ],
            options={
                "db_table": "charm_release",
                "ordering": ["charm", "track", "risk"],
                "indexes": [
                    models.Index(fields=["charm"], name="charm_relea_charm_6e5e30_idx")
                ],
                "unique_together": {("charm", "track", "risk")},
            },
        ),
    ]
