#!/usr/bin/env bash
#
# setup_local.sh — install and configure everything IS-CMDB needs to run locally.
#
# Two modes, auto-detected:
#   1. Docker present  -> brings the whole stack up with docker compose (the path
#                         documented in docker-compose.yml).
#   2. No Docker        -> provisions Python, PostgreSQL and Redis into a self
#                         contained conda environment + a local Postgres data dir
#                         under .pgdata/, with no root/sudo required.
#
# The script is idempotent: re-running it reuses the conda env, the Postgres data
# directory and the database instead of recreating them.
#
# Usage:
#   ./scripts/setup_local.sh            # set everything up (and run migrations)
#   ./scripts/setup_local.sh --no-start # set up but do not start Postgres/Redis
#
# Note: no `set -u` — conda's activation hooks reference unset vars and would trip it.
set -eo pipefail

# --- locate repo root (this script lives in <root>/scripts) ---------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

CONDA_ENV_NAME="cmdb"
PGDATA="$ROOT_DIR/.pgdata"
PGPORT="5432"
REDIS_PORT="6379"
DB_NAME="cmdb"
DB_USER="cmdb"
DB_PASS="cmdb"

START_SERVICES=1
[[ "${1:-}" == "--no-start" ]] && START_SERVICES=0

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }

# ------------------------------------------------------------------------------
# Mode 1: Docker
# ------------------------------------------------------------------------------
if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "Docker detected — using docker compose (db + redis + web)."
    docker compose up --build -d
    log "Stack is up. Web UI: http://localhost:8000/   API docs: http://localhost:8000/api/docs/"
    log "Logs:  docker compose logs -f web"
    log "Stop:  docker compose down"
    exit 0
fi

warn "Docker not found — falling back to a local conda-based setup (no root required)."

# ------------------------------------------------------------------------------
# Mode 2: conda + local Postgres/Redis
# ------------------------------------------------------------------------------
command -v conda >/dev/null 2>&1 || die "conda not found. Install Miniconda/Anaconda, or install Docker, then re-run."

# Make `conda activate` usable inside this non-interactive shell.
CONDA_BASE="$(conda info --base)"
# shellcheck disable=SC1091
source "$CONDA_BASE/etc/profile.d/conda.sh"

# --- 1. conda env with Python + PostgreSQL + Redis server ----------------------
if conda env list | awk '{print $1}' | grep -qx "$CONDA_ENV_NAME"; then
    log "conda env '$CONDA_ENV_NAME' already exists — reusing it."
else
    log "Creating conda env '$CONDA_ENV_NAME' (python 3.12 + postgresql + redis)..."
    conda create -y -n "$CONDA_ENV_NAME" -c conda-forge python=3.12 postgresql redis
fi
conda activate "$CONDA_ENV_NAME"

# --- 2. Python dependencies ----------------------------------------------------
log "Installing Python dependencies from requirements.txt..."
pip install -r requirements.txt

# --- 3. .env -------------------------------------------------------------------
if [[ -f .env ]]; then
    log ".env already exists — leaving it untouched."
else
    log "Writing .env for local development."
    cat > .env <<EOF
# Local development settings (generated by scripts/setup_local.sh)
SECRET_KEY=dev-insecure-key-change-in-production
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1

DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:${PGPORT}/${DB_NAME}
REDIS_URL=redis://localhost:${REDIS_PORT}/0
EOF
fi

# --- 4. PostgreSQL data directory ---------------------------------------------
if [[ -d "$PGDATA" ]]; then
    log "Postgres data dir already initialised ($PGDATA)."
else
    log "Initialising Postgres data dir at $PGDATA ..."
    initdb -D "$PGDATA" -U "$DB_USER" --auth=trust --encoding=UTF8 >/dev/null
fi

if [[ "$START_SERVICES" -eq 0 ]]; then
    log "Setup complete (--no-start). Start services later with: ./scripts/run_local.sh"
    exit 0
fi

# --- 5. Start Postgres ---------------------------------------------------------
if pg_ctl -D "$PGDATA" status >/dev/null 2>&1; then
    log "Postgres already running."
else
    log "Starting Postgres on port ${PGPORT}..."
    pg_ctl -D "$PGDATA" -l "$PGDATA/server.log" -o "-k /tmp -p ${PGPORT}" -w start
fi

# --- 6. Create the application database ----------------------------------------
if psql -h localhost -p "$PGPORT" -U "$DB_USER" -lqt | cut -d'|' -f1 | grep -qw "$DB_NAME"; then
    log "Database '$DB_NAME' already exists."
else
    log "Creating database '$DB_NAME'..."
    createdb -h localhost -p "$PGPORT" -U "$DB_USER" "$DB_NAME"
fi

# --- 7. Start Redis ------------------------------------------------------------
if redis-cli -p "$REDIS_PORT" ping >/dev/null 2>&1; then
    log "Redis already running."
else
    log "Starting Redis on port ${REDIS_PORT}..."
    redis-server --daemonize yes --port "$REDIS_PORT" --dir /tmp
fi

# --- 8. Django migrations ------------------------------------------------------
log "Applying Django migrations..."
python manage.py migrate

# --- 9. Clone the source repos if not present ---------------------------------
# Three git-ignored siblings the CMDB ingests: infrastructure-services (parser),
# plus is-terraform-models + is-terraform-modules (charm/GitOps resolution — the
# refresh_* commands fail without them).
INFRA_DIR="$ROOT_DIR/infrastructure-services"
if command -v gh >/dev/null 2>&1; then
    # is-terraform-models + is-terraform-modules: needed by refresh_service_charms,
    # refresh_charms and refresh_gitops.
    for repo in is-terraform-models is-terraform-modules; do
        dest="$ROOT_DIR/$repo"
        if [[ -d "$dest/.git" ]]; then
            log "$repo already cloned — skipping."
        else
            log "Cloning canonical/$repo..."
            gh repo clone "canonical/$repo" "$dest"
        fi
    done

    if [[ -d "$INFRA_DIR/.git" ]]; then
        log "infrastructure-services already cloned — skipping."
    else
        log "Cloning canonical/infrastructure-services..."
        gh repo clone canonical/infrastructure-services "$INFRA_DIR"
        log "Running initial parser to populate the database..."
        python "$ROOT_DIR/parser/parser.py" \
            --source "$INFRA_DIR" \
            --database-url "postgresql://${DB_USER}:${DB_PASS}@localhost:${PGPORT}/${DB_NAME}"
    fi
else
    warn "gh CLI not found — skipping source repo clones."
    warn "Install gh and run:"
    warn "  gh repo clone canonical/infrastructure-services"
    warn "  gh repo clone canonical/is-terraform-models"
    warn "  gh repo clone canonical/is-terraform-modules"
    warn "Then seed the DB with:  python manage.py import_csv environments.csv"
fi

# --- 10. Install daily sync cron job ------------------------------------------
CRON_LINE="0 3 * * * ${ROOT_DIR}/scripts/sync_infra_services.sh >> ${ROOT_DIR}/logs/sync.log 2>&1"
if crontab -l 2>/dev/null | grep -qF "sync_infra_services.sh"; then
    log "Daily sync cron job already installed."
else
    ( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -
    log "Installed daily sync cron job (runs at 03:00)."
fi

log "Setup complete."
echo
log "Start the web server with:"
echo "    conda activate ${CONDA_ENV_NAME} && python manage.py runserver"
echo
log "Then open:  http://127.0.0.1:8000/    (API docs: http://127.0.0.1:8000/api/docs/)"
log "Or run ./scripts/run_local.sh to start services + server together."
log "Stop the background DB/Redis with ./scripts/stop_local.sh"
