# Generated by Django 4.2.30 on 2026-06-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0007_environment_primary_node_environment_secondary_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("bucket_name", models.CharField(max_length=255)),
                ("cloud", models.CharField(db_index=True, max_length=50)),
                (
                    "owner_team",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("size_gb", models.FloatField(default=0.0)),
                ("object_count", models.IntegerField(default=0)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("radosgw", "RadosGW"), ("s3", "S3"), ("gcs", "GCS")],
                        default="radosgw",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "storage_resources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StorageEnvironmentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_type", models.CharField(default="readwrite", max_length=50)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_accesses",
                        to="environments.environment",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environment_accesses",
                        to="storage.storageresource",
                    ),
                ),
            ],
            options={
                "db_table": "storage_environment_access",
                "unique_together": {("storage", "environment")},
            },
        ),
    ]
