# Generated by Django 4.2.30 on 2026-06-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("netbox", "0001_initial"),
        ("environments", "0007_environment_primary_node_environment_secondary_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "pagerduty_window_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_windows",
                        to="netbox.node",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_windows",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceNotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("pagerduty", "PagerDuty"),
                            ("mattermost", "Mattermost"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="maintenance.maintenancewindow",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_notification_channels",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindowEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="environments.environment",
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenancewindow",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance_window_environments",
                "unique_together": {("window", "environment")},
            },
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["node", "status"], name="maintenance_node_id_847919_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["status", "starts_at"], name="maintenance_status_f27e82_idx"
            ),
        ),
    ]
