# Generated by Django 4.2.30 on 2026-06-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netbox", "0003_cloudstakeholder"),
        ("environments", "0007_environment_primary_node_environment_secondary_node"),
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancewindow",
            name="cloud",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Cloud slug for cloud-scoped windows.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="cos_silence_id",
            field=models.CharField(
                blank=True,
                help_text="Alertmanager/COS silence id (env scope).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maintenancewindow",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_windows",
                to="environments.environment",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancenotificationchannel",
            name="channel",
            field=models.CharField(
                choices=[
                    ("pagerduty", "PagerDuty"),
                    ("cos", "COS / Alertmanager"),
                    ("mattermost", "Mattermost"),
                    ("email", "Email"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancewindow",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_windows",
                to="netbox.node",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["cloud", "status"], name="maintenance_cloud_d57a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancewindow",
            index=models.Index(
                fields=["environment", "status"], name="maintenance_environ_9966e2_idx"
            ),
        ),
    ]
