"""PostgreSQL schema + history-preserving access (data-model.md §2, FR-028).

Fetched-data rows are append-only, keyed by ``fetch_id``; they are never
updated or deleted, so each fetch is a full historical layer. State/config
tables (role schedule, overrides, ui_state) keep history via row versioning —
the latest row wins on read, older rows are retained.

Backed by PostgreSQL (the app is deployed as a Kubernetes 12-factor charm whose
container filesystem is ephemeral). A small ``psycopg`` connection pool makes the
otherwise-synchronous access safe across the web replica(s) and the refresh
scheduler. Raw, full-fidelity fetch payloads live in the ``raw_snapshot`` JSONB
table rather than on disk.
"""

from __future__ import annotations

import json
from collections.abc import Iterable
from datetime import date, datetime
from typing import Any

from psycopg.rows import dict_row
from psycopg.types.json import Jsonb
from psycopg_pool import ConnectionPool

from ..domain.models import (
    PULSE_SUMMARY_FIELDS,
    Alert,
    AlertState,
    CalendarAvail,
    FetchSnapshot,
    GitHubPRStats,
    Pulse,
    Ticket,
    TouchEvent,
    TouchKind,
    WeekendOnCall,
)

# Connection string for local dev; the charm injects POSTGRESQL_DB_CONNECT_STRING.
DEFAULT_DSN = "postgresql:///standup_dashboard"

# Columns of open_summary_count, in order — the live open-work summary metrics.
_OPEN_SUMMARY_KEYS = ("highest", "ps5", "ps5_highest", "pr_mp", "escalated", "ongoing_alerts")

# ``start``/``end`` are SQL keywords (``end`` is reserved in PostgreSQL), so the
# pulse table quotes them in DDL and inserts.
SCHEMA = """
CREATE TABLE IF NOT EXISTS fetch_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fetched_at    TEXT NOT NULL,
    -- NULL = source not attempted in this fetch (per-source schedule, #per-source-schedule);
    -- 1 = ok, 0 = attempted-and-failed. Distinguishing the three keeps the failure banner
    -- and the incremental-window anchors correct when sources fetch independently.
    jira_ok       INTEGER,
    pagerduty_ok  INTEGER,
    ical_ok       INTEGER,
    raw_path      TEXT NOT NULL DEFAULT '',
    -- A partial, single-person refresh (#person-refresh): its tickets/touches still
    -- merge in, but it must NOT anchor the global incremental Jira window.
    partial       INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ticket (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    id             TEXT NOT NULL,
    project_key    TEXT NOT NULL,
    title          TEXT NOT NULL,
    status         TEXT NOT NULL,
    priority       TEXT,
    labels_json    TEXT NOT NULL,
    assignee_email TEXT,
    sprint_id      BIGINT,
    is_done_date   TEXT,
    created        TEXT,
    status_category TEXT,
    reporter_email TEXT,
    wip_since      TEXT,
    estimate_seconds INTEGER,
    spent_seconds    INTEGER,
    PRIMARY KEY (fetch_id, id)
);

CREATE TABLE IF NOT EXISTS touch_event (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    ticket_id      TEXT NOT NULL,
    engineer_email TEXT NOT NULL,
    kind           TEXT NOT NULL,
    at             TEXT NOT NULL,
    seconds        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (fetch_id, ticket_id, engineer_email, kind, at)
);

CREATE TABLE IF NOT EXISTS alert (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    id             TEXT NOT NULL,
    handler_email  TEXT NOT NULL,
    state          TEXT NOT NULL,
    at             TEXT NOT NULL,
    title          TEXT,
    url            TEXT,
    number         INTEGER,
    PRIMARY KEY (fetch_id, id, handler_email, state)
);

CREATE TABLE IF NOT EXISTS pulse (
    fetch_id     BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    project_key  TEXT NOT NULL,
    sprint_id    BIGINT NOT NULL,
    name         TEXT NOT NULL,
    "start"      TEXT NOT NULL,
    "end"        TEXT NOT NULL,
    state        TEXT NOT NULL,
    -- Keyed by sprint, not project: a board can run several concurrent active
    -- sprints (its own + a shared cross-team one), and all of them belong to the
    -- pulse, so each must persist (#172).
    PRIMARY KEY (fetch_id, sprint_id)
);

-- One row per distinct PagerDuty incident, deduped across fetches and NOT
-- pruned — the long-lived year history for repeat-offender analysis (#146).
-- Bootstrapped from the historical backfill, topped up by every refresh.
CREATE TABLE IF NOT EXISTS incident (
    id         TEXT PRIMARY KEY,
    signature  TEXT NOT NULL,
    fired_at   TEXT NOT NULL,
    title      TEXT,
    number     INTEGER,
    url        TEXT
);
CREATE INDEX IF NOT EXISTS idx_incident_sig ON incident (signature);
CREATE INDEX IF NOT EXISTS idx_incident_fired ON incident (fired_at);

CREATE TABLE IF NOT EXISTS weekend_oncall (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    engineer_email TEXT NOT NULL,
    weekend_start  TEXT NOT NULL,
    weekend_end    TEXT NOT NULL,
    PRIMARY KEY (fetch_id, engineer_email, weekend_start)
);

-- Per-engineer per-pulse PR activity for the "GH PRs" card line (#173).
CREATE TABLE IF NOT EXISTS github_pr (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    engineer_email TEXT NOT NULL,
    created        INTEGER NOT NULL DEFAULT 0,
    merged         INTEGER NOT NULL DEFAULT 0,
    updated        INTEGER NOT NULL DEFAULT 0,
    reviewed       INTEGER NOT NULL DEFAULT 0,
    created_24h    INTEGER NOT NULL DEFAULT 0,
    merged_24h     INTEGER NOT NULL DEFAULT 0,
    updated_24h    INTEGER NOT NULL DEFAULT 0,
    reviewed_24h   INTEGER NOT NULL DEFAULT 0,
    created_today  INTEGER NOT NULL DEFAULT 0,
    merged_today   INTEGER NOT NULL DEFAULT 0,
    updated_today  INTEGER NOT NULL DEFAULT 0,
    reviewed_today INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (fetch_id, engineer_email)
);

-- Per-engineer calendar occupancy this pulse from the free/busy iCal feed (#cal).
CREATE TABLE IF NOT EXISTS calendar_avail (
    fetch_id       BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    engineer_email TEXT NOT NULL,
    busy_seconds   INTEGER NOT NULL DEFAULT 0,
    open_seconds   INTEGER NOT NULL DEFAULT 0,
    pto_seconds    INTEGER NOT NULL DEFAULT 0,
    sd_days        TEXT NOT NULL DEFAULT '',
    busy_today     INTEGER NOT NULL DEFAULT 0,
    open_today     INTEGER NOT NULL DEFAULT 0,
    busy_24h       INTEGER NOT NULL DEFAULT 0,
    open_24h       INTEGER NOT NULL DEFAULT 0,
    pto_days       TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (fetch_id, engineer_email)
);

-- Live open-work summary counts taken straight from the saved Jira filters / JQL
-- and PagerDuty the summary line links to — one row per fetch (current snapshot,
-- latest fetch wins). NULL = that count was unavailable this fetch (#summary-live).
CREATE TABLE IF NOT EXISTS open_summary_count (
    fetch_id       BIGINT NOT NULL PRIMARY KEY REFERENCES fetch_snapshot(id),
    highest        INTEGER,
    ps5            INTEGER,
    ps5_highest    INTEGER,
    pr_mp          INTEGER,
    escalated      INTEGER,
    ongoing_alerts INTEGER
);

-- Full-fidelity raw fetch payloads (Jira/PagerDuty JSON, oncall.ics), append-only
-- and never pruned. Stored as JSONB; independent of the normalised schema (FR-028).
CREATE TABLE IF NOT EXISTS raw_snapshot (
    fetch_id  BIGINT NOT NULL REFERENCES fetch_snapshot(id),
    name      TEXT NOT NULL,
    payload   JSONB NOT NULL,
    PRIMARY KEY (fetch_id, name)
);

CREATE TABLE IF NOT EXISTS role_schedule (
    engineer_email TEXT NOT NULL,
    weekday        TEXT NOT NULL,
    role           TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS role_override (
    engineer_email TEXT NOT NULL,
    role           TEXT NOT NULL,
    effective_date TEXT NOT NULL,
    expires_at     TEXT NOT NULL,
    created_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS day_note (
    engineer_email TEXT NOT NULL,
    weekday        TEXT NOT NULL DEFAULT '',  -- legacy per-weekday key (#day-notes)
    note_date      TEXT NOT NULL DEFAULT '',  -- ISO date; the per-date key
    note           TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);

-- email → Jira accountId (#sprint-link): persisted from the fetch so the card can
-- link to a person's sprint board by accountId (works for private-email engineers).
CREATE TABLE IF NOT EXISTS jira_account (
    email      TEXT PRIMARY KEY,
    account_id TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ui_state (
    key        TEXT NOT NULL,
    value      TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS roster_addition (
    email        TEXT NOT NULL,
    name         TEXT NOT NULL,
    region       TEXT NOT NULL,
    github_login TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS region_override (
    email      TEXT NOT NULL,
    region     TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pulse_summary (
    pulse_number    INTEGER NOT NULL,
    region          TEXT NOT NULL,
    new_highest     INTEGER NOT NULL,
    new_pr_mp       INTEGER NOT NULL,
    new_ps5         INTEGER NOT NULL,
    new_regular     INTEGER NOT NULL,
    new_total       INTEGER NOT NULL,
    closed_highest  INTEGER NOT NULL,
    closed_pr_mp    INTEGER NOT NULL DEFAULT 0,
    closed_ps5      INTEGER NOT NULL,
    closed_total    INTEGER NOT NULL,
    isdb_closed     INTEGER NOT NULL DEFAULT 0,
    alerts_triggered INTEGER NOT NULL DEFAULT 0,
    alerts_ack      INTEGER NOT NULL,
    alerts_resolved INTEGER NOT NULL,
    alerts_total    INTEGER NOT NULL,
    alert_mttr_sum  INTEGER NOT NULL DEFAULT 0,
    alert_mttr_n    INTEGER NOT NULL DEFAULT 0,
    alert_mtta_sum  INTEGER NOT NULL DEFAULT 0,
    alert_mtta_n    INTEGER NOT NULL DEFAULT 0,
    ticket_cycle_sum INTEGER NOT NULL DEFAULT 0,
    ticket_cycle_n   INTEGER NOT NULL DEFAULT 0,
    breakdowns_json TEXT,
    updated_at      TEXT NOT NULL,
    PRIMARY KEY (pulse_number, region)
);

-- Columns added after a table first shipped: idempotent ADDs so existing
-- databases pick them up on the next start (CREATE TABLE IF NOT EXISTS won't).
-- Must run before the indexes below, which reference the new columns.
ALTER TABLE calendar_avail ADD COLUMN IF NOT EXISTS pto_days TEXT NOT NULL DEFAULT '';
-- Day notes moved from a recurring weekday slot to a specific date (#day-notes).
ALTER TABLE day_note ADD COLUMN IF NOT EXISTS note_date TEXT NOT NULL DEFAULT '';
ALTER TABLE day_note ALTER COLUMN weekday SET DEFAULT '';
-- Jira time-tracking on tickets: estimate vs invested on ISDB lines (#isdb-estimate).
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS estimate_seconds INTEGER;
ALTER TABLE ticket ADD COLUMN IF NOT EXISTS spent_seconds INTEGER;
-- Single-person partial refresh marker (#person-refresh).
ALTER TABLE fetch_snapshot ADD COLUMN IF NOT EXISTS partial INTEGER NOT NULL DEFAULT 0;
-- Per-source schedule (#per-source-schedule): a not-attempted source is NULL, so the
-- ok-flags must allow NULL (older DBs created them NOT NULL).
ALTER TABLE fetch_snapshot ALTER COLUMN jira_ok DROP NOT NULL;
ALTER TABLE fetch_snapshot ALTER COLUMN pagerduty_ok DROP NOT NULL;
ALTER TABLE fetch_snapshot ALTER COLUMN ical_ok DROP NOT NULL;

CREATE INDEX IF NOT EXISTS idx_role_schedule_latest
    ON role_schedule (engineer_email, weekday, updated_at);
CREATE INDEX IF NOT EXISTS idx_day_note_latest
    ON day_note (engineer_email, note_date, updated_at);
CREATE INDEX IF NOT EXISTS idx_ui_state_latest
    ON ui_state (key, updated_at);
"""


class Database:
    """Thin PostgreSQL wrapper. History-preserving by construction.

    Holds a small ``psycopg`` connection pool; every statement borrows a pooled
    connection that commits on clean block exit. ``dict_row`` gives named-column
    access (``row["col"]``), mirroring the previous ``sqlite3.Row``.
    """

    def __init__(self, dsn: str = DEFAULT_DSN):
        self.dsn = dsn
        self._pool = ConnectionPool(
            conninfo=dsn, min_size=1, max_size=10,
            kwargs={"row_factory": dict_row}, open=True,
        )
        # CREATE TABLE/INDEX IF NOT EXISTS — idempotent; safe on every start. The
        # DDL has no parameters, so psycopg runs the whole multi-statement script
        # in one execute().
        self._execute(SCHEMA)

    # -- low-level helpers ---------------------------------------------------

    def _execute(self, sql: str, params: tuple | list = ()) -> None:
        with self._pool.connection() as conn, conn.cursor() as cur:
            cur.execute(sql, params)

    def _executemany(self, sql: str, seq: list[tuple]) -> None:
        rows = list(seq)
        if not rows:
            return
        with self._pool.connection() as conn, conn.cursor() as cur:
            cur.executemany(sql, rows)

    def _fetchone(self, sql: str, params: tuple | list = ()) -> dict[str, Any] | None:
        with self._pool.connection() as conn, conn.cursor() as cur:
            cur.execute(sql, params)
            return cur.fetchone()

    def _fetchall(self, sql: str, params: tuple | list = ()) -> list[dict[str, Any]]:
        with self._pool.connection() as conn, conn.cursor() as cur:
            cur.execute(sql, params)
            return cur.fetchall()

    def close(self) -> None:
        self._pool.close()

    # -- fetch snapshots -----------------------------------------------------

    def create_fetch_snapshot(
        self,
        fetched_at: datetime,
        jira_ok: bool | None,
        pagerduty_ok: bool | None,
        ical_ok: bool | None,
        raw_path: str = "",
        partial: bool = False,
    ) -> int:
        # None → NULL: that source wasn't attempted in this fetch (#per-source-schedule).
        nb = lambda v: None if v is None else int(v)  # noqa: E731
        row = self._fetchone(
            "INSERT INTO fetch_snapshot"
            " (fetched_at, jira_ok, pagerduty_ok, ical_ok, raw_path, partial)"
            " VALUES (%s, %s, %s, %s, %s, %s) RETURNING id",
            (fetched_at.isoformat(), nb(jira_ok), nb(pagerduty_ok), nb(ical_ok),
             raw_path, int(partial)),
        )
        return int(row["id"])

    def upsert_account_ids(self, mapping: dict[str, str]) -> None:
        """Persist email → Jira accountId for sprint board links (#sprint-link)."""
        if not mapping:
            return
        self._executemany(
            "INSERT INTO jira_account (email, account_id) VALUES (%s, %s)"
            " ON CONFLICT (email) DO UPDATE SET account_id = EXCLUDED.account_id",
            [(e, a) for e, a in mapping.items()],
        )

    def get_account_ids(self) -> dict[str, str]:
        rows = self._fetchall("SELECT email, account_id FROM jira_account")
        return {r["email"]: r["account_id"] for r in rows}

    def latest_source_ok(self, column: str) -> bool | None:
        """Result of the most recent fetch that *attempted* this source (#per-source-
        schedule): True ok / False failed / None never attempted. ``column`` is one of
        the internal ok-flag names (not user input). Drives the per-source failure banner."""
        if column not in ("jira_ok", "pagerduty_ok", "ical_ok"):
            raise ValueError(column)
        row = self._fetchone(
            f"SELECT {column} AS v FROM fetch_snapshot"
            f" WHERE {column} IS NOT NULL ORDER BY id DESC LIMIT 1"
        )
        return None if row is None else bool(row["v"])

    def latest_fetch(self) -> FetchSnapshot | None:
        row = self._fetchone("SELECT * FROM fetch_snapshot ORDER BY id DESC LIMIT 1")
        return _row_to_snapshot(row) if row else None

    def latest_good_fetch(self) -> FetchSnapshot | None:
        """Most recent *full* snapshot where Jira succeeded — the anchor for the
        incremental Jira window. Partial single-person refreshes are excluded so they
        never truncate the global window to one person's data (#person-refresh)."""
        row = self._fetchone(
            "SELECT * FROM fetch_snapshot WHERE jira_ok = 1 AND partial = 0"
            " ORDER BY id DESC LIMIT 1"
        )
        return _row_to_snapshot(row) if row else None

    def latest_pagerduty_fetch(self) -> FetchSnapshot | None:
        """Most recent snapshot where PagerDuty succeeded — the start point for
        the incremental alert window (mirrors ``latest_good_fetch`` for Jira)."""
        row = self._fetchone(
            "SELECT * FROM fetch_snapshot WHERE pagerduty_ok = 1 ORDER BY id DESC LIMIT 1"
        )
        return _row_to_snapshot(row) if row else None

    def last_refresh_at(self) -> datetime | None:
        """When the most recent refresh ran (any source), or None if never."""
        snap = self.latest_fetch()
        return snap.fetched_at if snap else None

    def count_fetch_snapshots(self) -> int:
        row = self._fetchone("SELECT COUNT(*) AS n FROM fetch_snapshot")
        return int(row["n"])

    def fetches_since(self, since: datetime) -> list[FetchSnapshot]:
        """All snapshots fetched at/after ``since``, oldest first (for merging, #88)."""
        rows = self._fetchall(
            "SELECT * FROM fetch_snapshot WHERE fetched_at >= %s ORDER BY id ASC",
            (since.isoformat(),),
        )
        return [_row_to_snapshot(r) for r in rows]

    # -- append-only writes of fetched data ----------------------------------

    def insert_tickets(self, fetch_id: int, tickets: Iterable[Ticket]) -> None:
        self._executemany(
            "INSERT INTO ticket"
            " (fetch_id, id, project_key, title, status, priority, labels_json,"
            "  assignee_email, sprint_id, is_done_date, created, status_category,"
            "  reporter_email, wip_since, estimate_seconds, spent_seconds)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            " ON CONFLICT DO NOTHING",
            [
                (
                    fetch_id, t.id, t.project_key, t.title, t.status, t.priority,
                    json.dumps(t.labels), t.assignee_email, t.sprint_id,
                    t.is_done_date.isoformat() if t.is_done_date else None,
                    t.created.isoformat() if t.created else None,
                    t.status_category, t.reporter_email,
                    t.wip_since.isoformat() if t.wip_since else None,
                    t.estimate_seconds, t.spent_seconds,
                )
                for t in tickets
            ],
        )

    def insert_touches(self, fetch_id: int, touches: Iterable[TouchEvent]) -> None:
        self._executemany(
            "INSERT INTO touch_event"
            " (fetch_id, ticket_id, engineer_email, kind, at, seconds)"
            " VALUES (%s, %s, %s, %s, %s, %s) ON CONFLICT DO NOTHING",
            [(fetch_id, t.ticket_id, t.engineer_email, t.kind.value, t.at.isoformat(),
              t.seconds) for t in touches],
        )

    def insert_alerts(self, fetch_id: int, alerts: Iterable[Alert]) -> None:
        self._executemany(
            "INSERT INTO alert"
            " (fetch_id, id, handler_email, state, at, title, url, number)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s, %s) ON CONFLICT DO NOTHING",
            [(fetch_id, a.id, a.handler_email, a.state.value, a.at.isoformat(),
              a.title, a.url, a.number) for a in alerts],
        )

    def insert_raw_snapshots(self, fetch_id: int, payloads: dict[str, Any]) -> None:
        """Persist full-fidelity raw fetch payloads as JSONB (replaces the old
        on-disk snapshot writer). ``payloads`` maps a name (e.g. ``jira_search.json``
        or ``oncall.ics``) to a JSON-serialisable object or a raw string."""
        self._executemany(
            "INSERT INTO raw_snapshot (fetch_id, name, payload) VALUES (%s, %s, %s)"
            " ON CONFLICT DO NOTHING",
            [(fetch_id, name, Jsonb(payload)) for name, payload in payloads.items()],
        )

    def upsert_incidents(self, records: Iterable) -> None:
        """Accumulate distinct incidents into the long-lived ``incident`` table.

        Keeps the earliest ``fired_at`` and back-fills title/number/url from
        whichever event first carried them (idempotent across refreshes)."""
        self._executemany(
            "INSERT INTO incident (id, signature, fired_at, title, number, url)"
            " VALUES (%s, %s, %s, %s, %s, %s)"
            " ON CONFLICT (id) DO UPDATE SET"
            "   fired_at = LEAST(incident.fired_at, EXCLUDED.fired_at),"
            "   signature = COALESCE(NULLIF(EXCLUDED.signature, ''), incident.signature),"
            "   title = COALESCE(NULLIF(EXCLUDED.title, ''), incident.title),"
            "   number = COALESCE(incident.number, EXCLUDED.number),"
            "   url = COALESCE(incident.url, EXCLUDED.url)",
            [(r.id, r.signature, r.fired_at.isoformat(), r.title, r.number, r.url)
             for r in records],
        )

    def incident_meta(
        self, ids: Iterable[str]
    ) -> dict[str, tuple[str | None, int | None, str | None]]:
        """incident id → (title, number, url) from the long-lived incident table."""
        ids = list(dict.fromkeys(ids))
        if not ids:
            return {}
        rows = self._fetchall(
            "SELECT id, title, number, url FROM incident WHERE id = ANY(%s)", (ids,)
        )
        return {r["id"]: (r["title"], r["number"], r["url"]) for r in rows}

    def get_incidents_since(self, since: datetime) -> list[dict[str, Any]]:
        """Raw incident rows fired at/after ``since`` (the service maps them)."""
        return self._fetchall(
            "SELECT id, signature, fired_at, title, number, url"
            " FROM incident WHERE fired_at >= %s",
            (since.isoformat(),),
        )

    def insert_pulses(self, fetch_id: int, pulses: Iterable[Pulse]) -> None:
        self._executemany(
            'INSERT INTO pulse'
            ' (fetch_id, project_key, sprint_id, name, "start", "end", state)'
            ' VALUES (%s, %s, %s, %s, %s, %s, %s) ON CONFLICT DO NOTHING',
            [(fetch_id, p.project_key, p.sprint_id, p.name,
              p.start.isoformat(), p.end.isoformat(), p.state) for p in pulses],
        )

    def insert_weekend_oncall(self, fetch_id: int, entries: Iterable[WeekendOnCall]) -> None:
        self._executemany(
            "INSERT INTO weekend_oncall"
            " (fetch_id, engineer_email, weekend_start, weekend_end)"
            " VALUES (%s, %s, %s, %s) ON CONFLICT DO NOTHING",
            [(fetch_id, w.engineer_email, w.weekend_start.isoformat(), w.weekend_end.isoformat())
             for w in entries],
        )

    def insert_github_prs(
        self, fetch_id: int, pulse: dict[str, GitHubPRStats],
        day: dict[str, GitHubPRStats], today: dict[str, GitHubPRStats],
    ) -> None:
        """Persist per-engineer PR activity — pulse + last 24h + today (#173)."""
        rows = []
        for email, p in pulse.items():
            d = day.get(email, GitHubPRStats())
            t = today.get(email, GitHubPRStats())
            rows.append((fetch_id, email, p.created, p.merged, p.updated, p.reviewed,
                         d.created, d.merged, d.updated, d.reviewed,
                         t.created, t.merged, t.updated, t.reviewed))
        self._executemany(
            "INSERT INTO github_pr"
            " (fetch_id, engineer_email, created, merged, updated, reviewed,"
            "  created_24h, merged_24h, updated_24h, reviewed_24h,"
            "  created_today, merged_today, updated_today, reviewed_today)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
            " ON CONFLICT DO NOTHING", rows,
        )

    def get_github_prs(
        self, fetch_id: int
    ) -> tuple[dict[str, GitHubPRStats], dict[str, GitHubPRStats], dict[str, GitHubPRStats]]:
        """(pulse, last-24h, today) per-engineer PR stats for this fetch."""
        rows = self._fetchall(
            "SELECT engineer_email, created, merged, updated, reviewed,"
            " created_24h, merged_24h, updated_24h, reviewed_24h,"
            " created_today, merged_today, updated_today, reviewed_today"
            " FROM github_pr WHERE fetch_id = %s", (fetch_id,)
        )
        pulse = {r["engineer_email"]: GitHubPRStats(
            r["created"], r["merged"], r["updated"], r["reviewed"]) for r in rows}
        day = {r["engineer_email"]: GitHubPRStats(
            r["created_24h"], r["merged_24h"], r["updated_24h"], r["reviewed_24h"])
            for r in rows}
        today = {r["engineer_email"]: GitHubPRStats(
            r["created_today"], r["merged_today"], r["updated_today"], r["reviewed_today"])
            for r in rows}
        return pulse, day, today

    def insert_open_summary(self, fetch_id: int, counts: dict[str, int]) -> None:
        """Persist this fetch's live open-work counts (#summary-live). A missing key
        stores NULL so the presenter falls back to a local tally for that metric."""
        vals = [counts.get(k) for k in _OPEN_SUMMARY_KEYS]
        self._execute(
            "INSERT INTO open_summary_count"
            " (fetch_id, highest, ps5, ps5_highest, pr_mp, escalated, ongoing_alerts)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s) ON CONFLICT DO NOTHING",
            (fetch_id, *vals),
        )

    def get_open_summary(self, fetch_id: int) -> dict[str, int]:
        """Live open-work counts for this fetch — only the keys with a stored value."""
        rows = self._fetchall(
            "SELECT highest, ps5, ps5_highest, pr_mp, escalated, ongoing_alerts"
            " FROM open_summary_count WHERE fetch_id = %s", (fetch_id,)
        )
        if not rows:
            return {}
        r = rows[0]
        return {k: r[k] for k in _OPEN_SUMMARY_KEYS if r[k] is not None}

    def insert_calendar_avail(self, fetch_id: int, avail: dict[str, CalendarAvail]) -> None:
        """Persist per-engineer calendar busy/open — pulse + today + 24h (#cal)."""
        self._executemany(
            "INSERT INTO calendar_avail"
            " (fetch_id, engineer_email, busy_seconds, open_seconds, pto_seconds, sd_days,"
            "  busy_today, open_today, busy_24h, open_24h, pto_days)"
            " VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) ON CONFLICT DO NOTHING",
            [(fetch_id, email, a.busy_seconds, a.open_seconds, a.pto_seconds,
              ",".join(a.sd_days), a.busy_today_seconds, a.open_today_seconds,
              a.busy_24h_seconds, a.open_24h_seconds, "|".join(a.pto_days))
             for email, a in avail.items()],
        )

    def get_calendar_avail(self, fetch_id: int) -> dict[str, CalendarAvail]:
        rows = self._fetchall(
            "SELECT engineer_email, busy_seconds, open_seconds, pto_seconds, sd_days,"
            " busy_today, open_today, busy_24h, open_24h, pto_days"
            " FROM calendar_avail WHERE fetch_id = %s", (fetch_id,)
        )
        return {
            r["engineer_email"]: CalendarAvail(
                busy_seconds=r["busy_seconds"], open_seconds=r["open_seconds"],
                pto_seconds=r["pto_seconds"],
                sd_days=tuple(d for d in r["sd_days"].split(",") if d),
                has_data=True,
                busy_today_seconds=r["busy_today"], open_today_seconds=r["open_today"],
                busy_24h_seconds=r["busy_24h"], open_24h_seconds=r["open_24h"],
                pto_days=tuple(d for d in (r["pto_days"] or "").split("|") if d))
            for r in rows
        }

    # -- reads of a fetch layer ----------------------------------------------

    def get_tickets(self, fetch_id: int) -> list[Ticket]:
        rows = self._fetchall("SELECT * FROM ticket WHERE fetch_id = %s", (fetch_id,))
        return [_row_to_ticket(r) for r in rows]

    def get_touches(self, fetch_id: int) -> list[TouchEvent]:
        rows = self._fetchall("SELECT * FROM touch_event WHERE fetch_id = %s", (fetch_id,))
        return [
            TouchEvent(r["ticket_id"], r["engineer_email"], TouchKind(r["kind"]),
                       datetime.fromisoformat(r["at"]), seconds=r["seconds"])
            for r in rows
        ]

    def get_alerts(self, fetch_id: int) -> list[Alert]:
        rows = self._fetchall("SELECT * FROM alert WHERE fetch_id = %s", (fetch_id,))
        return [
            Alert(r["id"], r["handler_email"], AlertState(r["state"]),
                  datetime.fromisoformat(r["at"]), title=r["title"], url=r["url"],
                  number=r["number"])
            for r in rows
        ]

    def get_pulses(self, fetch_id: int) -> list[Pulse]:
        rows = self._fetchall("SELECT * FROM pulse WHERE fetch_id = %s", (fetch_id,))
        return [
            Pulse(r["project_key"], r["sprint_id"], r["name"],
                  datetime.fromisoformat(r["start"]), datetime.fromisoformat(r["end"]), r["state"])
            for r in rows
        ]

    def get_weekend_oncall(self, fetch_id: int) -> list[WeekendOnCall]:
        rows = self._fetchall("SELECT * FROM weekend_oncall WHERE fetch_id = %s", (fetch_id,))
        return [
            WeekendOnCall(r["engineer_email"], date.fromisoformat(r["weekend_start"]),
                          date.fromisoformat(r["weekend_end"]))
            for r in rows
        ]

    # -- role schedule (latest row wins per engineer+weekday) ----------------

    def set_weekly_role(self, engineer_email: str, weekday: str, role: str,
                        now: datetime) -> None:
        self._execute(
            "INSERT INTO role_schedule (engineer_email, weekday, role, updated_at)"
            " VALUES (%s, %s, %s, %s)",
            (engineer_email, weekday, role, now.isoformat()),
        )

    def get_weekly_schedule(self) -> dict[tuple[str, str], str]:
        """Latest role per (engineer_email, weekday)."""
        rows = self._fetchall(
            "SELECT engineer_email, weekday, role FROM role_schedule rs"
            " WHERE updated_at = ("
            "   SELECT MAX(updated_at) FROM role_schedule"
            "   WHERE engineer_email = rs.engineer_email AND weekday = rs.weekday)"
        )
        return {(r["engineer_email"], r["weekday"]): r["role"] for r in rows}

    # -- day notes (latest row wins per engineer+date, #day-notes) -----------

    def set_day_note(self, engineer_email: str, note_date: str, note: str,
                     now: datetime) -> None:
        """Set/clear a free-text note for a specific ISO date (``YYYY-MM-DD``)."""
        self._execute(
            "INSERT INTO day_note (engineer_email, note_date, note, updated_at)"
            " VALUES (%s, %s, %s, %s)",
            (engineer_email, note_date, note, now.isoformat()),
        )

    def get_day_notes(self) -> dict[tuple[str, str], str]:
        """Latest free-text day note per (engineer_email, ISO date)."""
        rows = self._fetchall(
            "SELECT engineer_email, note_date, note FROM day_note dn"
            " WHERE note_date <> '' AND updated_at = ("
            "   SELECT MAX(updated_at) FROM day_note"
            "   WHERE engineer_email = dn.engineer_email AND note_date = dn.note_date)"
        )
        return {(r["engineer_email"], r["note_date"]): r["note"] for r in rows}

    # -- role override -------------------------------------------------------

    def set_override(self, engineer_email: str, role: str, effective_date: date,
                     expires_at: datetime, now: datetime) -> None:
        self._execute(
            "INSERT INTO role_override"
            " (engineer_email, role, effective_date, expires_at, created_at)"
            " VALUES (%s, %s, %s, %s, %s)",
            (engineer_email, role, effective_date.isoformat(), expires_at.isoformat(),
             now.isoformat()),
        )

    def get_active_overrides(self, now: datetime) -> dict[str, str]:
        """Latest non-expired override role per engineer (expires_at > now)."""
        rows = self._fetchall(
            "SELECT engineer_email, role, expires_at, created_at FROM role_override ro"
            " WHERE expires_at > %s"
            " AND created_at = ("
            "   SELECT MAX(created_at) FROM role_override"
            "   WHERE engineer_email = ro.engineer_email AND expires_at > %s)",
            (now.isoformat(), now.isoformat()),
        )
        return {r["engineer_email"]: r["role"] for r in rows}

    # -- ui_state ------------------------------------------------------------

    def set_ui_state(self, key: str, value: str, now: datetime) -> None:
        self._execute(
            "INSERT INTO ui_state (key, value, updated_at) VALUES (%s, %s, %s)",
            (key, value, now.isoformat()),
        )

    def get_ui_state(self, key: str, default: str | None = None) -> str | None:
        row = self._fetchone(
            "SELECT value FROM ui_state WHERE key = %s ORDER BY updated_at DESC LIMIT 1",
            (key,),
        )
        return row["value"] if row else default

    # -- roster overrides (added engineers + region moves, #16) --------------

    def add_roster_engineer(
        self, name: str, email: str, region: str, now: datetime, github_login: str = ""
    ) -> None:
        self._execute(
            "INSERT INTO roster_addition (email, name, region, github_login, created_at)"
            " VALUES (%s, %s, %s, %s, %s)",
            (email, name, region, github_login, now.isoformat()),
        )

    def get_roster_additions(self) -> list[tuple[str, str, str, str]]:
        """Latest (name, email, region, github_login) per added engineer."""
        rows = self._fetchall(
            "SELECT name, email, region, github_login FROM roster_addition ra WHERE created_at = ("
            "  SELECT MAX(created_at) FROM roster_addition WHERE email = ra.email)"
        )
        return [(r["name"], r["email"], r["region"], r["github_login"]) for r in rows]

    def set_region_override(self, email: str, region: str, now: datetime) -> None:
        self._execute(
            "INSERT INTO region_override (email, region, updated_at) VALUES (%s, %s, %s)",
            (email, region, now.isoformat()),
        )

    def get_region_overrides(self) -> dict[str, str]:
        """Latest region per engineer that has been moved."""
        rows = self._fetchall(
            "SELECT email, region FROM region_override ro WHERE updated_at = ("
            "  SELECT MAX(updated_at) FROM region_override WHERE email = ro.email)"
        )
        return {r["email"]: r["region"] for r in rows}

    # -- pulse summaries (growing per-pulse history, #80) --------------------

    def upsert_pulse_summary(self, pulse_number: int, region: str,
                             metrics: dict[str, int], breakdowns: dict[str, dict[str, int]],
                             now: datetime, *, replace: bool = True) -> None:
        """Store one pulse/region summary.

        ``replace=True`` (default) overwrites any existing row — used for the
        authoritative current pulse and the backfill. ``replace=False`` only
        fills a gap (``DO NOTHING``): the live previous-pulse persist must not
        clobber an already-stored summary, because once a pulse falls behind the
        PagerDuty hard floor / Jira window the live snapshot can't see its full
        alert/ticket span and would zero out good history (#80 backfill).
        """
        upd_cols = (*PULSE_SUMMARY_FIELDS, "breakdowns_json", "updated_at")
        cols = ", ".join(PULSE_SUMMARY_FIELDS)
        placeholders = ", ".join("%s" for _ in PULSE_SUMMARY_FIELDS)
        values = [int(metrics.get(f, 0)) for f in PULSE_SUMMARY_FIELDS]
        if replace:
            sets = ", ".join(f"{c} = EXCLUDED.{c}" for c in upd_cols)
            conflict = f"DO UPDATE SET {sets}"
        else:
            conflict = "DO NOTHING"
        self._execute(
            f"INSERT INTO pulse_summary"
            f" (pulse_number, region, {cols}, breakdowns_json, updated_at)"
            f" VALUES (%s, %s, {placeholders}, %s, %s)"
            f" ON CONFLICT (pulse_number, region) {conflict}",
            (pulse_number, region, *values, json.dumps(breakdowns), now.isoformat()),
        )

    def get_pulse_summaries(
        self,
    ) -> list[tuple[int, str, dict[str, int], dict[str, dict[str, int]]]]:
        rows = self._fetchall("SELECT * FROM pulse_summary")
        out = []
        for r in rows:
            counts = {f: r[f] for f in PULSE_SUMMARY_FIELDS}
            breakdowns = json.loads(r["breakdowns_json"]) if r["breakdowns_json"] else {}
            out.append((r["pulse_number"], r["region"], counts, breakdowns))
        return out


def _row_to_snapshot(row: dict[str, Any]) -> FetchSnapshot:
    nb = lambda v: None if v is None else bool(v)  # noqa: E731 — preserve not-attempted
    return FetchSnapshot(
        id=row["id"],
        fetched_at=datetime.fromisoformat(row["fetched_at"]),
        jira_ok=nb(row["jira_ok"]),
        pagerduty_ok=nb(row["pagerduty_ok"]),
        ical_ok=nb(row["ical_ok"]),
        raw_path=row["raw_path"],
    )


def _row_to_ticket(row: dict[str, Any]) -> Ticket:
    return Ticket(
        id=row["id"],
        project_key=row["project_key"],
        title=row["title"],
        status=row["status"],
        priority=row["priority"],
        labels=json.loads(row["labels_json"]),
        assignee_email=row["assignee_email"],
        sprint_id=row["sprint_id"],
        is_done_date=date.fromisoformat(row["is_done_date"]) if row["is_done_date"] else None,
        created=datetime.fromisoformat(row["created"]) if row["created"] else None,
        status_category=row["status_category"],
        reporter_email=row["reporter_email"],
        wip_since=datetime.fromisoformat(row["wip_since"]) if row["wip_since"] else None,
        estimate_seconds=row.get("estimate_seconds"),
        spent_seconds=row.get("spent_seconds"),
    )
