# Generated by Django 4.2.30 on 2026-06-09 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netbox_id", models.IntegerField(unique=True)),
                (
                    "hostname",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("site", models.CharField(max_length=100)),
                ("cloud", models.CharField(db_index=True, max_length=50)),
                ("role", models.CharField(max_length=100)),
                ("rack", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=50)),
                ("primary_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("uplink_redundancy", models.BooleanField(default=False)),
                (
                    "physical_completeness",
                    models.FloatField(
                        default=0.0,
                        help_text="0.0-1.0; fraction of interfaces with cable records",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nodes",
                "ordering": ["hostname"],
            },
        ),
        migrations.CreateModel(
            name="NodeInterface",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netbox_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("mac_address", models.CharField(blank=True, max_length=17, null=True)),
                ("speed_mbps", models.IntegerField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interfaces",
                        to="netbox.node",
                    ),
                ),
            ],
            options={
                "db_table": "node_interfaces",
                "ordering": ["node", "name"],
            },
        ),
        migrations.CreateModel(
            name="NodeCable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("netbox_id", models.IntegerField(unique=True)),
                ("cable_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "interface_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cables_as_a",
                        to="netbox.nodeinterface",
                    ),
                ),
                (
                    "interface_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cables_as_b",
                        to="netbox.nodeinterface",
                    ),
                ),
            ],
            options={
                "db_table": "node_cables",
            },
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(
                fields=["cloud", "status"], name="nodes_cloud_439ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="node",
            index=models.Index(fields=["site"], name="nodes_site_ba6494_idx"),
        ),
    ]
