# Generated by Django 4.2.30 on 2026-06-09 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("netbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeSwitchConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("switch_hostname", models.CharField(db_index=True, max_length=255)),
                ("interface_name", models.CharField(max_length=100)),
                ("port_name", models.CharField(max_length=100)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="switch_connections",
                        to="netbox.node",
                    ),
                ),
            ],
            options={
                "db_table": "node_switch_connections",
                "ordering": ["node", "switch_hostname"],
            },
        ),
    ]
