# Generated by Django 4.2.30 on 2026-06-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox", "0002_nodeswitchconnection"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudStakeholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_slug", models.CharField(db_index=True, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cloud_stakeholders",
                "ordering": ["cloud_slug", "email"],
                "unique_together": {("cloud_slug", "email")},
            },
        ),
    ]
