# Generated by Django 4.2.30 on 2026-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox", "0003_cloudstakeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="host_aggregate",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="OpenStack host aggregate the hypervisor belongs to (e.g. production, builders, critical, SRIOV, staging).",
                max_length=100,
                null=True,
            ),
        ),
    ]
