# Generated by Django 4.2.30 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarAvail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("engineer_email", models.TextField()),
                ("busy_seconds", models.IntegerField()),
                ("open_seconds", models.IntegerField()),
                ("pto_seconds", models.IntegerField()),
                ("sd_days", models.TextField()),
                ("busy_today", models.IntegerField()),
                ("open_today", models.IntegerField()),
                ("busy_24h", models.IntegerField()),
                ("open_24h", models.IntegerField()),
                ("pto_days", models.TextField()),
            ],
            options={
                "db_table": "standup_calendar_avail",
            },
        ),
        migrations.CreateModel(
            name="DayNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engineer_email", models.TextField()),
                ("weekday", models.TextField()),
                ("note", models.TextField()),
                ("updated_at", models.TextField()),
                ("note_date", models.TextField()),
            ],
            options={
                "db_table": "standup_day_note",
            },
        ),
        migrations.CreateModel(
            name="FetchSnapshot",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("fetched_at", models.TextField()),
                ("jira_ok", models.IntegerField(blank=True, null=True)),
                ("pagerduty_ok", models.IntegerField(blank=True, null=True)),
                ("ical_ok", models.IntegerField(blank=True, null=True)),
                ("raw_path", models.TextField()),
                ("partial", models.IntegerField()),
            ],
            options={
                "db_table": "standup_fetch_snapshot",
            },
        ),
        migrations.CreateModel(
            name="GithubPr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("engineer_email", models.TextField()),
                ("created", models.IntegerField()),
                ("merged", models.IntegerField()),
                ("updated", models.IntegerField()),
                ("reviewed", models.IntegerField()),
                ("created_24h", models.IntegerField()),
                ("merged_24h", models.IntegerField()),
                ("updated_24h", models.IntegerField()),
                ("reviewed_24h", models.IntegerField()),
                ("created_today", models.IntegerField()),
                ("merged_today", models.IntegerField()),
                ("updated_today", models.IntegerField()),
                ("reviewed_today", models.IntegerField()),
            ],
            options={
                "db_table": "standup_github_pr",
            },
        ),
        migrations.CreateModel(
            name="JiraAccount",
            fields=[
                ("email", models.TextField(primary_key=True, serialize=False)),
                ("account_id", models.TextField()),
            ],
            options={
                "db_table": "standup_jira_account",
            },
        ),
        migrations.CreateModel(
            name="OpenSummaryCount",
            fields=[
                ("fetch_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("highest", models.IntegerField(blank=True, null=True)),
                ("ps5", models.IntegerField(blank=True, null=True)),
                ("ps5_highest", models.IntegerField(blank=True, null=True)),
                ("pr_mp", models.IntegerField(blank=True, null=True)),
                ("escalated", models.IntegerField(blank=True, null=True)),
                ("ongoing_alerts", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "standup_open_summary_count",
            },
        ),
        migrations.CreateModel(
            name="Pulse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("project_key", models.TextField()),
                ("sprint_id", models.BigIntegerField()),
                ("name", models.TextField()),
                ("start", models.TextField()),
                ("end", models.TextField()),
                ("state", models.TextField()),
            ],
            options={
                "db_table": "standup_pulse",
            },
        ),
        migrations.CreateModel(
            name="PulseSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pulse_number", models.IntegerField()),
                ("region", models.TextField()),
                ("new_highest", models.IntegerField()),
                ("new_pr_mp", models.IntegerField()),
                ("new_ps5", models.IntegerField()),
                ("new_regular", models.IntegerField()),
                ("new_total", models.IntegerField()),
                ("closed_highest", models.IntegerField()),
                ("closed_pr_mp", models.IntegerField()),
                ("closed_ps5", models.IntegerField()),
                ("closed_total", models.IntegerField()),
                ("isdb_closed", models.IntegerField()),
                ("alerts_triggered", models.IntegerField()),
                ("alerts_ack", models.IntegerField()),
                ("alerts_resolved", models.IntegerField()),
                ("alerts_total", models.IntegerField()),
                ("alert_mttr_sum", models.IntegerField()),
                ("alert_mttr_n", models.IntegerField()),
                ("alert_mtta_sum", models.IntegerField()),
                ("alert_mtta_n", models.IntegerField()),
                ("ticket_cycle_sum", models.IntegerField()),
                ("ticket_cycle_n", models.IntegerField()),
                ("breakdowns_json", models.TextField(blank=True, null=True)),
                ("updated_at", models.TextField()),
            ],
            options={
                "db_table": "standup_pulse_summary",
            },
        ),
        migrations.CreateModel(
            name="RawSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("name", models.TextField()),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "standup_raw_snapshot",
            },
        ),
        migrations.CreateModel(
            name="RegionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField()),
                ("region", models.TextField()),
                ("updated_at", models.TextField()),
            ],
            options={
                "db_table": "standup_region_override",
            },
        ),
        migrations.CreateModel(
            name="RoleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engineer_email", models.TextField()),
                ("role", models.TextField()),
                ("effective_date", models.TextField()),
                ("expires_at", models.TextField()),
                ("created_at", models.TextField()),
            ],
            options={
                "db_table": "standup_role_override",
            },
        ),
        migrations.CreateModel(
            name="RoleSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engineer_email", models.TextField()),
                ("weekday", models.TextField()),
                ("role", models.TextField()),
                ("updated_at", models.TextField()),
            ],
            options={
                "db_table": "standup_role_schedule",
            },
        ),
        migrations.CreateModel(
            name="RosterAddition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField()),
                ("name", models.TextField()),
                ("region", models.TextField()),
                ("github_login", models.TextField()),
                ("created_at", models.TextField()),
            ],
            options={
                "db_table": "standup_roster_addition",
            },
        ),
        migrations.CreateModel(
            name="StandupTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("ticket_key", models.TextField()),
                ("project_key", models.TextField()),
                ("title", models.TextField()),
                ("status", models.TextField()),
                ("priority", models.TextField(blank=True, null=True)),
                ("labels_json", models.TextField()),
                ("assignee_email", models.TextField(blank=True, null=True)),
                ("sprint_id", models.BigIntegerField(blank=True, null=True)),
                ("is_done_date", models.TextField(blank=True, null=True)),
                ("created", models.TextField(blank=True, null=True)),
                ("status_category", models.TextField(blank=True, null=True)),
                ("reporter_email", models.TextField(blank=True, null=True)),
                ("wip_since", models.TextField(blank=True, null=True)),
                ("estimate_seconds", models.IntegerField(blank=True, null=True)),
                ("spent_seconds", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "standup_ticket",
            },
        ),
        migrations.CreateModel(
            name="TouchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("ticket_id", models.TextField()),
                ("engineer_email", models.TextField()),
                ("kind", models.TextField()),
                ("at", models.TextField()),
                ("seconds", models.IntegerField()),
            ],
            options={
                "db_table": "standup_touch_event",
            },
        ),
        migrations.CreateModel(
            name="UiState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField()),
                ("value", models.TextField()),
                ("updated_at", models.TextField()),
            ],
            options={
                "db_table": "standup_ui_state",
            },
        ),
        migrations.CreateModel(
            name="WeekendOncall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fetch_id", models.BigIntegerField()),
                ("engineer_email", models.TextField()),
                ("weekend_start", models.TextField()),
                ("weekend_end", models.TextField()),
            ],
            options={
                "db_table": "standup_weekend_oncall",
            },
        ),
        migrations.AddConstraint(
            model_name="weekendoncall",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "engineer_email", "weekend_start"),
                name="uq_standup_weekend_oncall",
            ),
        ),
        migrations.AddIndex(
            model_name="touchevent",
            index=models.Index(
                fields=["engineer_email", "at"], name="ix_standup_touch_eng"
            ),
        ),
        migrations.AddConstraint(
            model_name="touchevent",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "ticket_id", "engineer_email", "kind", "at"),
                name="uq_standup_touch_event",
            ),
        ),
        migrations.AddIndex(
            model_name="standupticket",
            index=models.Index(fields=["ticket_key"], name="ix_standup_ticket_key"),
        ),
        migrations.AddConstraint(
            model_name="standupticket",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "ticket_key"), name="uq_standup_ticket"
            ),
        ),
        migrations.AddIndex(
            model_name="roleschedule",
            index=models.Index(
                fields=["engineer_email", "weekday"], name="ix_standup_role_sched"
            ),
        ),
        migrations.AddIndex(
            model_name="roleoverride",
            index=models.Index(fields=["engineer_email"], name="ix_standup_role_ovr"),
        ),
        migrations.AddConstraint(
            model_name="rawsnapshot",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "name"), name="uq_standup_raw_snapshot"
            ),
        ),
        migrations.AddConstraint(
            model_name="pulsesummary",
            constraint=models.UniqueConstraint(
                fields=("pulse_number", "region"), name="uq_standup_pulse_summary"
            ),
        ),
        migrations.AddConstraint(
            model_name="pulse",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "sprint_id"), name="uq_standup_pulse"
            ),
        ),
        migrations.AddConstraint(
            model_name="githubpr",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "engineer_email"), name="uq_standup_github_pr"
            ),
        ),
        migrations.AddIndex(
            model_name="daynote",
            index=models.Index(
                fields=["engineer_email", "note_date"], name="ix_standup_day_note"
            ),
        ),
        migrations.AddConstraint(
            model_name="calendaravail",
            constraint=models.UniqueConstraint(
                fields=("fetch_id", "engineer_email"), name="uq_standup_calendar_avail"
            ),
        ),
    ]
