# Generated by Django 4.2.30 on 2026-06-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseDayCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pulse_number", models.IntegerField()),
                ("region", models.TextField()),
                ("sort_order", models.IntegerField()),
                ("label", models.TextField()),
                ("day_start", models.TextField(blank=True, null=True)),
                ("day_end", models.TextField(blank=True, null=True)),
                ("is_weekend", models.BooleanField(default=False)),
                ("is_total", models.BooleanField(default=False)),
                ("new_highest", models.IntegerField(default=0)),
                ("new_pr_mp", models.IntegerField(default=0)),
                ("new_ps5", models.IntegerField(default=0)),
                ("new_regular", models.IntegerField(default=0)),
                ("new_total", models.IntegerField(default=0)),
                ("closed_highest", models.IntegerField(default=0)),
                ("closed_pr_mp", models.IntegerField(default=0)),
                ("closed_ps5", models.IntegerField(default=0)),
                ("closed_total", models.IntegerField(default=0)),
                ("isdb_closed", models.IntegerField(default=0)),
                ("alerts_triggered", models.IntegerField(default=0)),
                ("alerts_ack", models.IntegerField(default=0)),
                ("alerts_resolved", models.IntegerField(default=0)),
                ("alerts_total", models.IntegerField(default=0)),
                ("mttr_sum", models.IntegerField(default=0)),
                ("mttr_n", models.IntegerField(default=0)),
                ("mtta_sum", models.IntegerField(default=0)),
                ("mtta_n", models.IntegerField(default=0)),
                ("updated_at", models.TextField()),
            ],
            options={
                "db_table": "standup_pulse_day_count",
            },
        ),
        migrations.AddConstraint(
            model_name="pulsedaycount",
            constraint=models.UniqueConstraint(
                fields=("pulse_number", "region", "sort_order"),
                name="uq_standup_pulse_day_count",
            ),
        ),
    ]
