# Generated by Django 4.2.30 on 2026-06-24 05:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("netbox", "0005_load_host_aggregates"),
        ("environments", "0012_charmrelease"),
        ("maintenance", "0002_maintenancewindow_cloud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Change",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="CHG-YYYY-NNNN; assigned on submit.",
                        max_length=32,
                        null=True,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("normal", "Normal"),
                            ("emergency", "Emergency"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("awaiting_l1", "Awaiting L1 — Peer"),
                            ("awaiting_l2", "Awaiting L2 — Tech Lead"),
                            ("awaiting_l3", "Awaiting L3 — Change Manager"),
                            ("awaiting_l4", "Awaiting L4 — Consumer"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("verifying", "Verifying"),
                            ("applied", "Applied"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                            ("expired", "Expired"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="amer | emea | apac — derived from targets.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Bumps on any post-submit edit; resets the approval chain (§8.3).",
                    ),
                ),
                ("proposer", models.CharField(blank=True, max_length=255)),
                (
                    "executer",
                    models.CharField(
                        blank=True,
                        help_text="Regional SRE; required to submit.",
                        max_length=255,
                    ),
                ),
                ("peer_reviewer", models.CharField(blank=True, max_length=255)),
                ("precheck_commands", models.TextField(blank=True)),
                (
                    "execute_commands",
                    models.TextField(blank=True, help_text="Required to submit."),
                ),
                (
                    "verify_commands",
                    models.TextField(blank=True, help_text="Required to submit."),
                ),
                (
                    "rollback_commands",
                    models.TextField(blank=True, help_text="Required to submit."),
                ),
                ("risk_score", models.IntegerField(default=0)),
                (
                    "risk_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_duration", models.DurationField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("n/a", "N/A"),
                            ("success", "Success"),
                            ("rolled_back", "Rolled Back"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="n/a",
                        max_length=12,
                    ),
                ),
                ("pir_notes", models.TextField(blank=True)),
                ("gcal_event_id", models.CharField(blank=True, max_length=255)),
                ("freeze_override", models.BooleanField(default=False)),
                ("freeze_override_justification", models.TextField(blank=True)),
                (
                    "maintenance_window",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required to submit (completeness gate, §2.7).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changes",
                        to="maintenance.maintenancewindow",
                    ),
                ),
            ],
            options={
                "db_table": "changes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="Skip the CAB gate (peer-ack) when guardrails hold.",
                    ),
                ),
                ("requires_all_resilient", models.BooleanField(default=True)),
                ("max_nodes", models.PositiveIntegerField(blank=True, null=True)),
                ("allowed_target_types", models.JSONField(blank=True, default=list)),
                ("allowed_env_types", models.JSONField(blank=True, default=list)),
                ("allowed_clouds", models.JSONField(blank=True, default=list)),
                ("default_precheck_commands", models.TextField(blank=True)),
                ("default_execute_commands", models.TextField(blank=True)),
                ("default_verify_commands", models.TextField(blank=True)),
                ("default_rollback_commands", models.TextField(blank=True)),
                (
                    "owned_by",
                    models.CharField(
                        blank=True, default="is-management", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "change_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChangeTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("juju_model", "Juju model"),
                            ("node", "Node"),
                            ("switch", "Switch"),
                            ("cloud", "Cloud"),
                        ],
                        max_length=20,
                    ),
                ),
                ("switch_hostname", models.CharField(blank=True, max_length=255)),
                ("cloud", models.CharField(blank=True, max_length=50)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="changes.change",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_targets",
                        to="environments.environment",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_targets",
                        to="netbox.node",
                    ),
                ),
            ],
            options={
                "db_table": "change_targets",
            },
        ),
        migrations.CreateModel(
            name="ChangeNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("pagerduty", "PagerDuty"),
                            ("mattermost", "Mattermost"),
                            ("email", "Email"),
                            ("cos", "COS / Alertmanager"),
                            ("gcal", "Google Calendar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(blank=True, max_length=255)),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("resilient_blip", "Resilient blip"),
                            ("non_resilient_engineer", "Non-resilient — engineer"),
                            ("info", "Info"),
                            ("calendar_invite", "Calendar invite"),
                        ],
                        default="info",
                        max_length=24,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="changes.change",
                    ),
                ),
            ],
            options={
                "db_table": "change_notifications",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="The CR version this approval is for (§8.3).",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        help_text="L1=peer, L2=tech_lead, L3=change_manager (high-risk only), L4=consumer (always last)."
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("peer", "Peer"),
                            ("tech_lead", "Tech Lead"),
                            ("change_manager", "Change Manager"),
                            ("consumer", "Consumer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "party",
                    models.CharField(
                        blank=True,
                        help_text="IDP group / consuming-team slug.",
                        max_length=255,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("blocked", "Blocked (date)"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_by", models.CharField(blank=True, max_length=255)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "proposed_alternative_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="changes.change",
                    ),
                ),
            ],
            options={
                "db_table": "change_approvals",
                "ordering": ["version", "level", "party"],
            },
        ),
        migrations.AddField(
            model_name="change",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="changes",
                to="changes.changetemplate",
            ),
        ),
        migrations.CreateModel(
            name="ChangeAffectedEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("environment_name", models.CharField(db_index=True, max_length=255)),
                (
                    "impact_type",
                    models.CharField(
                        choices=[("direct", "Direct"), ("dependency", "Dependency")],
                        max_length=12,
                    ),
                ),
                ("dependency_depth", models.PositiveIntegerField(default=0)),
                ("resilient", models.BooleanField(default=False)),
                ("resilience_basis", models.CharField(blank=True, max_length=255)),
                ("consumer_team", models.CharField(blank=True, max_length=255)),
                ("criticality_tier", models.IntegerField(blank=True, null=True)),
                ("env_type", models.CharField(blank=True, max_length=20)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("ack_by", models.CharField(blank=True, max_length=255)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affected",
                        to="changes.change",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affected_by_changes",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "db_table": "change_affected_environments",
                "ordering": ["dependency_depth", "environment_name"],
                "unique_together": {("change", "environment_name")},
            },
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["status", "region"], name="changes_status_f91593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="change",
            index=models.Index(
                fields=["change_type", "risk_tier"], name="changes_change__540c6e_idx"
            ),
        ),
    ]
