# Generated by Django 4.2.30 on 2026-06-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="staging_notes",
            field=models.TextField(
                blank=True,
                help_text="Optional. Configuration that can be staged ahead of time without applying the change. Cold changes only.",
            ),
        ),
        migrations.AddField(
            model_name="change",
            name="temperature",
            field=models.CharField(
                choices=[("cold", "Cold"), ("hot", "Hot")],
                db_index=True,
                default="cold",
                help_text="Cold = offline/restarted for the change; hot = applied live. Independent of change_type; staging applies to cold only.",
                max_length=10,
            ),
        ),
    ]
