# Generated by Django 4.2.30 on 2026-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0002_change_staging_notes_change_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="change",
            name="temperature",
            field=models.CharField(
                choices=[("cold", "Outage (downtime)"), ("hot", "Live (no downtime)")],
                db_index=True,
                default="cold",
                help_text="Cold = offline/restarted for the change; hot = applied live. Independent of change_type; staging applies to cold only.",
                max_length=10,
            ),
        ),
    ]
