# Generated by Django 4.2.30 on 2026-06-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0003_alter_change_temperature"),
    ]

    operations = [
        migrations.AddField(
            model_name="change",
            name="notify_on_approval",
            field=models.BooleanField(
                default=False,
                help_text="Notify the impacted CIA owners (asset + risk owner) when the CR is approved.",
            ),
        ),
        migrations.AddField(
            model_name="changeaffectedenvironment",
            name="cia_owner",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="changeaffectedenvironment",
            name="cia_risk_owner",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
