# Generated by Django 4.2.30 on 2026-06-25 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changes", "0004_change_notify_on_approval_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardMaintenanceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[("amer", "AMER"), ("emea", "EMEA"), ("apac", "APAC")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=1,
                        help_text="Recurring day of week (Mon=0).",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Local start time within `timezone`."),
                ),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=14400)),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA tz name, e.g. Europe/London.",
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "standard_maintenance_windows",
                "ordering": ["region"],
            },
        ),
    ]
