# Generated by Django 4.2.30 on 2026-06-21 03:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environments", "0011_environment_gitops_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pd_id",
                    models.CharField(
                        db_index=True,
                        help_text="PagerDuty incident id, e.g. PT4KHLK.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("incident_number", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "Triggered"),
                            ("acknowledged", "Acknowledged"),
                            ("resolved", "Resolved"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        blank=True,
                        choices=[("high", "High"), ("low", "Low")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "service_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, help_text="Incident.created_at from PagerDuty."
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="last_status_change_at when status=resolved.",
                        null=True,
                    ),
                ),
                ("html_url", models.URLField(blank=True, null=True)),
                (
                    "cloud",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Cloud slug parsed from title or the matched env.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Owning team of the matched env, or PD team summary.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Trimmed raw PagerDuty payload for forensics.",
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now=True)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched via Environment.oncall_handle == service_id, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "db_table": "dora_incidents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cloud", "-created_at"],
                        name="dora_incide_cloud_041148_idx",
                    ),
                    models.Index(
                        fields=["team", "-created_at"],
                        name="dora_incide_team_cac470_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="dora_incide_status_d7a827_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeploymentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cloud",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        db_index=True,
                        help_text="Git SHA Flux reconciled to.",
                        max_length=40,
                    ),
                ),
                (
                    "kustomization",
                    models.CharField(
                        blank=True,
                        help_text="Flux Kustomization name/path; join key to Environment.gitops_path.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Author/commit timestamp of the SHA.",
                        null=True,
                    ),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        db_index=True, help_text="When Flux applied this revision."
                    ),
                ),
                (
                    "succeeded",
                    models.BooleanField(
                        default=True,
                        help_text="False = reconcile failed (change-failure signal).",
                    ),
                ),
                ("source", models.CharField(default="flux", max_length=20)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deployment_events",
                        to="environments.environment",
                    ),
                ),
            ],
            options={
                "db_table": "dora_deployment_events",
                "ordering": ["-reconciled_at"],
                "indexes": [
                    models.Index(
                        fields=["cloud", "-reconciled_at"],
                        name="dora_deploy_cloud_61fc15_idx",
                    ),
                    models.Index(
                        fields=["environment", "-reconciled_at"],
                        name="dora_deploy_environ_08358d_idx",
                    ),
                ],
                "unique_together": {("commit_sha", "kustomization")},
            },
        ),
    ]
